### ISSUE TITLE
Avoid fatal errors on dashboard

### ISSUE THREAD

**Issue by Mte90** [johnbillion/extended-cpts#202]
So on https://github.com/johnbillion/extended-cpts/search?q=glance_items the issue is on `array` on the function parameter that a lot of plugins and developer don't pass this filter with an array but null or string so this plugin creates a crash on our customer websites.
I want to avoid to keep a fork only for that change...

**Comment by johnbillion** [comment]
I know how annoying this is, but this really isn't a problem with Extended CPTs and should be fixed in the plugins that are not returning an array from this filter. If a plugin can't trust other plugins to return the correct type from a filter then all hope is lost and every callback for every filter should perform a type safety check as a guard condition.

Do you know which plugins are affected? I'm happy to speak with the authors and advise on corrective measures.

**Comment by Mte90** [comment]
Well in our issues we saw developers and plugins so I report when I found it, the problem is when they get a fatal error and blame us...
It is not possible to do a function that wrap the filter and check the input?

This issues are blocking us to use the library in premium plugins and not just on custom plugins where I know the environment plugin.

I want to avoid people that creates tickets or reach us on every social or email just to report a fatal error (because happens in those cases) on upgrading our plugin because I switched to the main repo.

**Comment by johnbillion** [comment]
Right, but this is papering over the issue instead of addressing the root cause, which is a bug in some code elsewhere.

This happened a few times with my User Switching plugin (which also uses type hinted parameters for filter callbacks) and it ultimately helped two users discover a security vulnerability in other plugins that were returning null from user capability filters. The PHP warnings had gone ignored.

Like I said, I'm happy to take a look at any plugins or themes that return an invalid type from this filter and help them fix it, but fixing this in Extended CPTs isn't the right place.
