### ISSUE TITLE
Autoload?

### ISSUE THREAD

**Issue by ekandreas** [johnbillion/extended-cpts#35]
Hi!
Thanks for a more cleaner version of extended-cpts!
I miss an autoload to the library as I use the package via Packagist in a WP Roots Bedrock installation.
Or do you have any example to load the lib when going via Composer?

**Comment by ekandreas** [comment]
Just add this to the composer.json-file and upgrade the version with one step:
```
	"autoload": {
		"files": ["extended-cpts.php"]
	}
```

I will make you a pull request...

**Comment by ekandreas** [comment]
Please! Any response to this?

**Comment by ekandreas** [comment]
If anyone is interested by autoload from your "local" composer setup without include_once inside your libs, you can add this to composer.json:
```
  "autoload": {
        "files": ["vendor/johnbillion/extended-cpts/extended-cpts.php"]
  }
```

**Comment by aaemnnosttv** [comment]
This is how I currently handle this in my Bedrock `composer.json`
```
"autoload": {
    "classmap": ["vendor/johnbillion"]
  },
```
Then, believe it or not, you can autoload the library as simple as this:
```php
class_exists('Extended_CPT', true);
```
That could also be part of a conditional to bail if the class did not exist, but it does the job since the class and the files live together.

I generally find that using the `files` key in the autoloader is best to be avoided when possible, because of the load timing.  The oscarotero/env library handles this well I think by using a static method on the main class for loading the functions to [expose the global functions](https://github.com/oscarotero/env#the-env-function).  This lets you use the optimal deferred class loading and only bring in the functions when needed - at the right time.

@ekandreas @vinkla

**Comment by ekandreas** [comment]
Sure, you can solve it that way but it is much better if the plugin provider care for loading the functions in the right time making it easy to use the lib.

**Comment by aaemnnosttv** [comment]
I agree 100%.  My suggestion was just that in this case there are better alternatives than using `files` for autoloading :)

**Comment by johnbillion** [comment]
The next version of Extended CPTs (and Extended Taxos) will use Composer's `files` pseudo-autoloading from #36.
