### ISSUE TITLE
Transatable label

### ISSUE THREAD

**Issue by Mte90** [johnbillion/extended-cpts#66]
Actually we can pass the singular and plural form of post type in that way is translatable but is not possible to pass the textdomain to translate the labels like "Add New".
In that way actually for non-english is a problem :-/

**Comment by johnbillion** [comment]
Thanks for the report, Daniele. I'm going to close this because although the library could accept a textdomain parameter and then pass it through to the `Add New` label, and any other labels which aren't specific to the post type, I think it makes more sense that if you need non-English labels then you should be specifying all of the labels. In some languages, `Add New` may vary depending on the post type even though the post type's name isn't present in the label text.

**Comment by Mte90** [comment]
Perfect, the important that the labels can be translated.
The readme is not updated yet :-)

**Comment by aitormendez** [comment]
Sorry if I missunderstand. How can I specify all other labels? I tryed 

```
[
    'add_new'  => __( 'Add New', 'txt-domain' )
]
```

As a third parameter of `register_extended_post_type`, but it doen't work.

**Comment by Mte90** [comment]
I am doing in that way https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/internals/class-posttypes.php#L124

**Comment by aitormendez** [comment]
Ok, I did it, but it just translate the CPT name. For example, 

`'singular' => __('Production', 'mrg-CPT'),`

Produces this spanish output for "new production": "new producción"

(note that "new" is not translated and "production" is translated).

**Comment by johnbillion** [comment]
You need to provide and translate the complete labels array in full, just as you would when you register a post type with WordPress' built-in `register_post_type()` function. Unfortunately there's nothing that Extended CPTs can do about this. The automatic label generation only works for English labels.

**Comment by aitormendez** [comment]
Ok. I got it. It works! Thank you.
