### ISSUE TITLE
Lowercase forced on certain labels

### ISSUE THREAD

**Issue by retlehs** [johnbillion/extended-cpts#76]
example on a post type for FAQs:

```
add_action('init', function () {
    register_extended_post_type('faq', [
        'menu_icon' => 'dashicons-editor-help'
    ], [
        'singular' => 'FAQ',
        'plural' => 'FAQs'
    ]);
});
```

results in "No faqs found" rather than "No FAQs found"

![image](https://user-images.githubusercontent.com/115911/29851282-822d671e-8cf0-11e7-9c5e-5d5641effda3.png)

**Comment by johnbillion** [comment]
Thanks for the report. I've made various tweaks to the way that labels are built in the past and I found that lowercasing the name makes sense most of the time, because an initialism as a post type name is relatively uncommon.

However, I have just had an idea. Maybe the label generation should respect the case if more than just the first letter in the name is capitalised. I'll have a play around with it.
