### ISSUE TITLE
Pass column/field value to callback in admin_cols

### ISSUE THREAD

**Issue by corradomatt** [johnbillion/extended-cpts#88]
I think it would be appropriate to pass the value returned to the admin column for a post to it's callback function when used with meta_key. It would help greatly when dealing with filtering the returned value before display in the admin column.

For example, I'm going to be using this with CMB2 and specifically an image field. The field returns the image URL and I'd like to display the image in the admin column. If the function callback accepted the meta_key value as it's argument, this would be trivial.

Thoughts?

**Comment by johnbillion** [comment]
Not passing any parameters to callback functions was an intentional design decision when I first wrote ExtCPTs, however I can't actually remember the underlying reason, and I suspect that it wasn't solid reasoning anyway.

That said, this is technically a breaking change, so I'd have to consider how best to go about this and what the desired behaviour for the callbacks for each type would be.

For now, you can get around this by using a closure:

```php
'story_published' => [
	'title'       => 'Published',
	'meta_key'    => 'published',
	'function'    => function() {
		my_function( 'published' );
	}
],
'story_discontinued' => [
	'title'       => 'Discontinued',
	'meta_key'    => 'discontinued',
	'function'    => function() {
		my_function( 'discontinued' );
	}
],
```

**Comment by corradomatt** [comment]
Thanks @johnbillion - that makes sense. I'll leave this issue open a few more days while you consider it ;)
